spring.application.name=coreproviderTrustly
logging.config=classpath:log4j2.xml

trustly.initiate.payment.url=http://localhost:8084/?token=

payment.notification.url=http://localhost:8082/trustly/notification

spring.profiles.active=@spring.profiles.active@

server.port=8084

